spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGIN}


supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  service-key: ${SERVICE_KEY}
  webhook:
    secret: ${WEBHOOK_SECRET}

