server:
  port: ${PORT:8080}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html

  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false