name: Build and Deploy Docker (Optimized)

on:
  push:
    branches:
      - dev

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin) and enable gradle cache
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build Jar (on runner)
        run: |
          ./gradlew clean bootJar -x test --no-daemon -Dorg.gradle.jvmargs="-Xmx2g -XX:+UseParallelGC"

      - name: Prepare image context
        run: |
          cp build/libs/*.jar app.jar

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set repo and image name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG=${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push runtime image (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Trigger Jenkins Deploy
        run: |
          DEPLOY_ENV=${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          curl -X POST \
               -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" \
               "https://${{ secrets.JENKINS_SERVER }}/job/production/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&DEPLOY_ENV=${DEPLOY_ENV}" \
               --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.API_TOKEN }}
